# Generated by Django 4.1.2 on 2023-03-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=15)),
                ("lastname", models.CharField(max_length=15)),
                ("emp_id", models.IntegerField()),
            ],
        ),
    ]
