# Generated by Django 4.1.2 on 2023-03-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("My_App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField()),
                ("created_by", models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(name="employee",),
    ]
